wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1653031667
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.16
      8:
      - 5
communication_range:
  desc: null
  value: 1
env_name:
  desc: null
  value: SenseBroadcastTrainer
environment_type_name:
  desc: null
  value: nonclustered_tile_grid
eval_model_name:
  desc: null
  value: null
experiment_name:
  desc: null
  value: delete_test
height:
  desc: null
  value: 25
initial_observations_useful:
  desc: null
  value: true
is_clustered:
  desc: null
  value: false
max_num_of_steps:
  desc: null
  value: 10
model_type:
  desc: null
  value: PPO
num_episodes:
  desc: null
  value: 100
num_of_swarm_agents:
  desc: null
  value: 12
offline:
  desc: null
  value: false
optimal_step_multiplier:
  desc: null
  value: 3.0
policy_type:
  desc: null
  value: MlpPolicy
previous_model:
  desc: null
  value: null
random_agent_per_step:
  desc: null
  value: true
ratio_of_white_to_black_tiles:
  desc: null
  value: 0.5
testing_environment:
  desc: null
  value: null
training_environment:
  desc: null
  value: skill_training_modules.skill_training_environments.sense_broadcast_trainer_env.SenseBroadcastTrainer
verbose:
  desc: null
  value: 1
width:
  desc: null
  value: 25
