import os

EXPERIMENT_DATA_ROOT_DIRECTORY = f"{os.getcwd()}/experiment_data"
LOGS_DIRECTORY = f"{EXPERIMENT_DATA_ROOT_DIRECTORY}/logs"
MODELS_DIRECTORY = f"{EXPERIMENT_DATA_ROOT_DIRECTORY}/models"
SETTINGS_DIRECTORY = f"{EXPERIMENT_DATA_ROOT_DIRECTORY}/settings"
STATISTICS_DIRECTORY = f"{EXPERIMENT_DATA_ROOT_DIRECTORY}/statistics"
